- package-lock.json
- package.json
- src/components/App.js
- src/components/candidate.js
- src/components/search.js
- src/index.js
added routing capability with 2 links as a start. Basic routing template so for additional routes should be relatively simple to add/change.
> Added routing c

- CONTRIBUTING.md
- README.md
Still need to add instructions on how to run the project and details about the project structure. I will add that after I get the backend setup
#27
> Update README and Add Content to Contributing

- server/api_doc.md
- server/index.js
- server/lib/search.js
Closes #40 
Added a contributor search function, endpoint, and documentation.
Added basic pagination with `offset` and `limit`.
For now the endpoints are documented in `server/api_doc.md` as the project grows we may consider using swagger or something else.
> Create contributor search endpoint and documentation

- package-lock.json
- package.json
- src/components/App.js
- src/components/Table.js
- src/components/candidate.js
- src/css/table.scss
Resolves #51 
Created a table component:
1. Using USWDS table styles
1. Using react-table
1. Each column filters using a autocomplete multi-select input
1. The table can be sorted asc/desc by each column
New dependencies:
1. `react-table` for table hooks
1. `match-sorter` for fuzzy matching while filtering (suggested in `react-table` docs)
1. `react-select` for select input components
TODO:
1. Fixed table sizing. Currently columns resize on filter
1. Disable sorting when clicking on filter input. Currently clicking any components in the table header will change sort order.
> Table comp

- CONTRIBUTING.md
- server/api_doc.md
- server/bin/etl.js
- server/index.js
- server/lib/search.js
- server/migrations/1596322414730_committee-table.js
Add candidate search by name endpoint. We will need to enhance later to allow for searching by other fields in the candidate data set.  
Also add a get candidate and contributions by ncsbe_id
> Add Candidate Search by Name

- src/components/App.js
@SchaeStewart probably could not have had a smaller first PR for this :)
> Fix import bug that prevents client from compiling

- package-lock.json
- server/api_doc.md
- server/index.js
- server/lib/queries.js
- server/package-lock.json
- server/package.json
closes #89 
blocked by #97 
Add query `toCSV` query param to the `candidate/:ncsbeID/contributions` endpoint.  
When `toCSV` is true, `offset` and `limit` will be ignored.
The endpoint should work if used as an `href` in an `a` tag, or if you `fetch` the results. When using it as an `href` the browser should automatically handle the file download.
> Download Candidate Donations as CSV

- package-lock.json
- package.json
- src/components/SearchBar.js
Resolves #88 
Changes
- Updated `@trussworks/react-uswds` to `1.9.1`
- Added placeholder text to the main search bar
- Reflects current status of MVP (user can search by Candidate or Donor)
- Based on wireframe: https://www.figma.com/proto/OcC48DWJjwCsPigGa9vb82/Campaign-Finance-Dashboard-Wireframes
Future dev
- Needs to be updated after we add support PAC/keyword search
> Add placeholder to search bar, update react-uswds

- .github/workflows/build-and-test.yml
Env vars weren't being substituted when following example I had found. Trying this way.
> Fix var references

- src/components/DataDictionary.js
- src/hooks/useApi.js
- src/static/dataDictionary.json
> Update data dictionary, fix sorting, and handle fetch sorting properly

- src/hooks/useApi.js
> Fix Search Failing

- src/components/Candidate.js
- src/css/candidate.scss
- src/hooks/useCandidate.js
Resolves #110 
**Test here:** `/candidate/177-AGM31F-C-001`
Changes:
1. Added a CSV download button
1. On click, fetches from the API endpoint, gets the response blob, creates a new temp URL, and opens it for the user to download
1. Can't just open the API route for CSV download through UI because React router catches it and just returns the default route.
1. Removed some unneeded `console.log()` statements
The only issue with this method is that the CSV files are downloaded with a random filename instead of a descriptive one.
> #110 CSV Download Button

- server/bin/exportToCSV.js
Small change, just adding the committees table to the exportToCSV
> Add committees to exportToCSV

- server/lib/queries.js
- server/test/test-routes.js
- src/components/Candidate.js
Changes:
- Added aggregate candidate info to summary
- Commented out some placeholder text. (I can move this to another commit if necessary)
- Updated tests
> Add aggregated contribution info to summary

- src/components/Table.js
> added optional chaining operator to avoid null ref error

- server/app.js
Reverts ncopenpass/CampaignFinance#142
> Revert "enforce ssl in production"

- server/app.js
Reverts ncopenpass/CampaignFinance#146
> Revert "Enforce SSL"

- src/components/Header.js
Resolves #145 where the mobile nav was not toggling.
> Enable Mobile Toggle of Navigation

- scripts/createDataDictionary.js
- src/components/DataDictionary.js
- src/static/dataDictionary.json
- Update values in the data dictionary
- Add a button at the bottom of the dictionary for going to SBOE manual
- Add a script for automatically extracting the data dictionary from a .txt file
> Update Data Dictionary and add script for automatically creating data dictionary

- src/hooks/useTableColumns.js
> added column accessor to Contribution Date

- src/hooks/useTableColumns.js
> formatted Amount column to USD

- src/hooks/useTableColumns.js
> Changed 3 column names and added 'Employer' column

- Makefile
- docs/scripts.md
- scripts/createDataDictionary.js
- add a scripts readme
- add a command to make file to build the data dictionary
- improve the script
> Improve data dictionary script usage

- server/api.js
- server/api_doc.md
- server/test/test-routes.js
Add candidate_name and committee_name to the GET /contributors/:contributorId/contributions route.
> Add candidate name and committee_name to contributors/:contributorId/contributions route

- server/api.js
- server/api_doc.md
- server/test/test-routes.js
- src/components/SearchBar.js
Nothing major. Just put the "2020 Contributors" quick search btn back up. 
Running into that "Error Fetching Data" again. @Dafondo when you run this PR locally and try to search, do you get an error? Just want to make sure I won't cause an error when this gets merged.
> Put the 2020 Contributors quick search btn back up.

- server/api.js
- server/api_doc.md
- server/test/test-routes.js
Co-authored-by: Schaffer Stewart <schaestewart@gmail.com>
> Add total_contributions_to_committee

- server/api.js
- server/api_doc.md
- server/lib/queries.js
- server/test/test-routes.js
> Add CSV download to contributors/:contributorId/contributions

- src/components/Candidate.js
- src/components/QuickSearchResults.js
- src/components/SearchResultTable.js
- src/components/SearchResults.js
- src/constants/common.js
- src/css/index.scss
- src/hooks/useCandidate.js
- src/hooks/useQuickSearch.js
- src/hooks/useSearch.js
fixes: #158
This would be easier to implement with a different API-fetch architecture
> First try at adding loading state to SearchResultTable

- src/components/Candidate.js
- src/hooks/useCandidate.js
- Fix count on contribution table on Candidate page
- Remove commented-out code
- Remove old `hasError` state variables
Fixes #201
> [201] Fix contribution count on Candidate page

- src/components/SearchBar.js
Removed quick results buttons on home page.
> Remove quick results btns

- src/hooks/useTableColumns.js
Removed "Comment" column and rearranged the columns.
> Update candidate table

- Makefile
- server/api/search.js
- server/api_doc.md
- server/lib/repr.js
- server/lib/search.js
- server/test/test-routes.js
- src/components/SearchResults.js
- src/hooks/useSearch.js
- src/hooks/useTableColumns.js
Changes:
- Add committee search API modeled after the candidate search API
- Add committees section to the table on the search results page
> Add Committee Search API and UI

- CONTRIBUTING.md
- README.md
- src/components/Committee.js
- src/hooks/useCommittee.js
Updated Figma and project board links.
> Updated links in readme and contributing.md.

- src/components/SearchBar.js
- update the search placeholder text
- remove unused code and its dependencies
- format
Fixes #221
> [221] Update Search Placeholder Text

- server/app.js
Related to #275 
Add middleware logging to the request handlers so we can see how long they are taking
> Add logHandlerTime middleware

- docker-compose.yml
Change database `shm_size` in docker-compose file 
I was hitting a memory or diskspace limit because of the latest contributions files size
n/a
n/a
n/a
> Fix docker memory size.

- src/components/Candidate.js
Make sure offset cannot be negative
Closes #304
Bug 304
> Bug 304 - fix pagination on candidate page

- server/api/contributor.js
- server/lib/queries.js
- src/components/Contributor.js
- src/hooks/useContributors.js
- src/hooks/useTableColumns.js
Adds the ability to sort contributor contributions by date and amount. Includes addition of table filters in the UI, as well as the sortBy field to the api and queries. Closes  https://github.com/ncopenpass/CampaignFinance/issues/235 and https://github.com/ncopenpass/CampaignFinance/issues/263.
Required functionality to sort contributor contributions by date and amount.
https://github.com/ncopenpass/CampaignFinance/issues/235
https://github.com/ncopenpass/CampaignFinance/issues/263
> feat: add contributor contributions sorting

- server/api_doc.md
Add documentation for years candidate received contributions
> Add documentation for years candidate received contributions

- server/api_doc.md
Add documentation for years committee received contributions
> Add documentation for years committee received contributions
