server/lib/search.js

Closes #73 (wherein is explained that users who put in term like "cooper" would not get any results).

Enable candidate searches to match on last name

---

server/api_doc.md
server/index.js
server/lib/queries.js

#closes #78 
Adds summary info to the `/candidate/:ncsbeID/contributions` endpoint.
If we want to move or add this to the `/candidate/:ncsbeID` endpoint I'd be okay with that. I had a hard time deciding where this info should go. I decided on the contributions endpoint because that's the page that will display the info.

#78 Add summary info to candidate contributions' endpoint

---

server/bin/etl.js

closes #99
The ETL script wasn't accounting for blank middle names when adding the `candidate_full_name` column. I fixed that, so now it will work for candidates with and without middle names

Fix messed up candidate_full_names

---

.github/workflows/build-and-test.yml
scripts/wait-for-postgres.sh
server/db/index.js

Tests were running before DB was accepting connection.
This adds a script and a step that calls the script to the build process to ensure DB is running and accepting connections before moving on to tests.

Wait for db to be ready before running tests in CI

---

src/analytics.js

There was a bug where safari was unable to evaluate the `window.external` browser object specific to Microsoft browsers.  Separated this into a different logic block that will only be evaluated if the browser is not Chromium, Webkit, or Gecko-based (only internet explorer).
This reference to `window.external` is IE-only specific code so it will only run if all other `doNotTrack` flags are undefined.
Tested in Chrome, Safari, and Firefox.  Not currently able to test in Edge, IE, or Opera.
Resolves #116.

Safari Fix

---

server/lib/search.js

In the contributor search query I split the contributor name on spaces and then use the first returned value.
So, `John Smith` should return when searching for `john` and, `06th Congressional District` will return if you search for `06th`

Enable contributor search by first name

---

server/api.js

Since the committees table contains data for candidates and committees, the quick search endpoint is returning data with blank `candidate_full_name` fields.
Ensure the candidate_full_name column is not blank when querying for candidates
Bug Example:

Bug Candidate quick search is returning blank results

---

server/app.js

Automatically redirect all requests to `https` if NODE_ENV is in production. I'm limited in how I can test this locally, so I will watch the deploy carefully and make sure it works

enforce ssl in production

---

src/components/Footer.js
src/components/SearchBar.js

Hid links we aren't using for now. Will remove them if we don't need them by the time we are ready to launch our next round of features. Hid Contributors quick search button until we have those tables ready.

Removed links from footer and hid contributors quick search.

---

server/api.js
server/api_doc.md
server/lib/search.js
server/package-lock.json
server/package.json

- Allow sorting of candidate results by `name` and `first_last_sml` (both `ASC` or `DESC`)
- Allow filtering of candidate results by `name`
- Allow filtering of candidate results by `contest`
- Allow filtering of candidate results by `party`
- update apidoc
Fixes #90

[90] Candidate sorting and filtering

---

server/api.js
server/api_doc.md
server/lib/queries.js

- Allow sorting of candidate contributor results by `name`, `amount` or `date_occurred`
- Allow filtering of candidate contributor results by `name` (fuzzy match)
- Allow filtering of candidate contributor results by `transaction_type` (exact match)
- Allow filtering of candidate contributor results by `amount` (exact match)
- Allow filtering of candidate contributor results by `form_of_payment` (exact match)
- Allow filtering of candidate contributor results by `date_occurred_gte` (greater than equal date filter)
- Allow filtering of candidate contributor results by `date_occurred_lte` (less than equal date filter)
- Update apidoc
Fixes #93

[93] Candidate Contributors sorting and filtering

---

server/api.js
server/api_doc.md
server/test/test-routes.js

Closes #174 
Added a GET `api/contributor/:contributorId` route which returns information for an individual contributor. If the id is not found, a 404 is returned and the body has a data field with a null value (see API doc for example).

Add GET /api/contributor/:contributorId

---

Makefile
docker-compose.yml
scripts/wait-for-postgres-local.sh
scripts/wait-for-postgres.sh

Docker startup sometimes fails on Mac. The issue appears to be that `make refresh-docker` exists before the database container is ready to accept connections. To fix this I modified the `wait-for-postgres.sh` script to read from the `.env` file if no URL is provided as an argument. I then added a `wait-for-postgres` step to the Makefile which is run after calling `refresh-docker`
I also change the restart policy of the containers in the docker-compose file to `on-failure` this should prevent the containers from automatically restarting when you restart your computer. (This was bugging me)

Fix Docker Startup Failing on Mac

---

src/hooks/useTableColumns.js

- sort contributor name by the correct key
Fixes #202

[202] Fix sorting bug for contributor table on Candidate page

---

src/components/Candidate.js
src/components/Contributor.js
src/components/Header.js
src/components/Table.js
src/hooks/useTableColumns.js

- Remove `back to search results` link
- Remove `fromPathname` route param
- Fix console errors related to Table spinner
- Fix TS compilation errors
Fixes #210 
Candidate Page
Contribution Page

[210] Remove 'back to search results' link. Fix other errors and warnings

---

src/components/Candidate.js
src/components/InputFilter.js
src/components/SearchResultTable.js
src/components/SearchResults.js
src/components/Table.js
src/css/index.scss
src/hooks/useCandidate.js
src/hooks/useSearch.js
src/hooks/useTableColumns.js

Add filtering for the tables on the Search Results page for all available filtering fields supported by the backend. Filters are text input fields with a 250ms debounce. See gif below for this feature in action.
Changes include:
- Convert onSortChange handling to generic data fetching
- Debounce filter and sort changes
- Rename columns variable name for search result page
- Remove existing component and types associated with old filtering
- Change defaultColumn to not enable filtering or sorting
- Add filters to api calls when they're provided
- Add new default Input filter component
- Add filtering to available columns on search results page
- Increase page content width on Search Results

Add filtering to tables on Search Results page

---

server/db/copyFromCSV.js

Add NULL delimiter to copyFromCSV. This tells postgres to treat the string `NULL` as the value `NULL` when doing the ETL. This fixes the problem with all the null fields in the data.
I have already tested these changes and uploaded a fresh dataset to prod. Now when searching you will not see a bunch of fields with the value `NULL`

Add NULL delimiter to copyFromCSV

---

server/lib/queries.js
server/test/test-routes.js

Fixes #277 
Apparently there were no tests for the committee routes. When I did the latest DB migration I didn't catch a column name change related to the committee summary route. I added tests to cover the 3 committee routes and I corrected the column name.

Fix Error On PAC Pages

---

server/api/expenditures.js
server/lib/queries.js
src/components/Candidate.js
src/components/Committee.js

#281: I added the `Download Results` button to the expenditures table for both the `Candidate` and `Committee` pages. So feel free to test on a candidate and non-candidate page and see if it works for you.

feat: add download results button to expenditures table

---

src/components/DataDictionary.js
src/static/dataDictionary.json

Technically #191 has been resolved but added this change instead of making a new ticket.
I updated `definition` in `dataDictionary.json` and `DataDictionary.js` to render as html so we can get those links to work instead of being a string.
It caused some table issues so I had to set a `minWidth` on the `Definition` column.
Before:
After:

fix: update data dictionary json to read links #191

---

server/lib/repr.js
server/test/test-routes.js
src/components/Candidate.js

Added the PAC name to the candidate page below `Contest`:
Also updated the candidate keys in the test file.
Resolves #245

feat: add pac name to candidate page

---

src/components/Table.js

#289 
Adjusted the css for the sorting arrows so they don't jump around when you click them.
Before:
After:
Even though I didn't really touch anything, I randomly get this error:
How to reproduce:
1. Go to Roy's candidate page
2. Click through the filters and then it should appear
I went to another candidate's page and I didn't get the error. I also can't reproduce it on the live website, so not sure what is happening 🤷‍♀️

fix: sort arrows not remaining fixed

---

src/hooks/useTableColumns.js

I updated tables to accommodate empty values for fields that could be empty like profession, employer, purpose, etc. I didn't do the columns that should have a value like name, location, total contributions, etc. Not sure if doing this in `useTableColumns.js` was the best way, but here we are. This should cover all tables on all pages.
Issue: #243

feat: add placeholder for empty table values

---

.github/pull_request_template.md

I guess I was having trouble with the "e" key when I typed this up originally. Fixed those spelling errors. Also made the headers less _aggressive_ 😅. Good news: it works when you open a PR! 🥳 
Because grammar
—
—

chore: fix spelling errors in pr markdown
